package com.lhd.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.lhd.entity.Classificationof;
import com.lhd.entity.ClassificationofExample;

public interface ClassificationofMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    long countByExample(ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int deleteByExample(ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int insert(Classificationof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int insertSelective(Classificationof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    List<Classificationof> selectByExample(ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    Classificationof selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Classificationof record, @Param("example") ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByExample(@Param("record") Classificationof record, @Param("example") ClassificationofExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(Classificationof record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByPrimaryKey(Classificationof record);
}