package com.lhd.dao;

import com.lhd.entity.Classificationofgoods;
import com.lhd.entity.ClassificationofgoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassificationofgoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    long countByExample(ClassificationofgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int deleteByExample(ClassificationofgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int insert(Classificationofgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int insertSelective(Classificationofgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    List<Classificationofgoods> selectByExample(ClassificationofgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    Classificationofgoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") Classificationofgoods record, @Param("example") ClassificationofgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int updateByExample(@Param("record") Classificationofgoods record, @Param("example") ClassificationofgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int updateByPrimaryKeySelective(Classificationofgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationofgoods
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    int updateByPrimaryKey(Classificationofgoods record);
}