package com.lhd.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.lhd.entity.ClassificationofGoodsItem;
import com.lhd.entity.ClassificationofGoodsItemExample;

public interface ClassificationofGoodsItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    long countByExample(ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int deleteByExample(ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int insert(ClassificationofGoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int insertSelective(ClassificationofGoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    List<ClassificationofGoodsItem> selectByExample(ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    ClassificationofGoodsItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") ClassificationofGoodsItem record, @Param("example") ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByExample(@Param("record") ClassificationofGoodsItem record, @Param("example") ClassificationofGoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(ClassificationofGoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classificationof_goods_item
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByPrimaryKey(ClassificationofGoodsItem record);
}