package com.lhd.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.lhd.entity.OrderList;
import com.lhd.entity.OrderListExample;

public interface OrderListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    long countByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int deleteByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int insert(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int insertSelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    List<OrderList> selectByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    OrderList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderList record, @Param("example") OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByExample(@Param("record") OrderList record, @Param("example") OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByPrimaryKey(OrderList record);
}