package com.lhd.dao;

import com.lhd.entity.TbPositionCounty;
import com.lhd.entity.TbPositionCountyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbPositionCountyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    long countByExample(TbPositionCountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int deleteByExample(TbPositionCountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int insert(TbPositionCounty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int insertSelective(TbPositionCounty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    List<TbPositionCounty> selectByExample(TbPositionCountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    TbPositionCounty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbPositionCounty record, @Param("example") TbPositionCountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByExample(@Param("record") TbPositionCounty record, @Param("example") TbPositionCountyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByPrimaryKeySelective(TbPositionCounty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_position_county
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    int updateByPrimaryKey(TbPositionCounty record);
}