package com.lhd.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.lhd.entity.UsersTable;
import com.lhd.entity.UsersTableExample;

public interface UsersTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    long countByExample(UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int deleteByExample(UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int insert(UsersTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int insertSelective(UsersTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    List<UsersTable> selectByExample(UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    UsersTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") UsersTable record, @Param("example") UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByExample(@Param("record") UsersTable record, @Param("example") UsersTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(UsersTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_table
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    int updateByPrimaryKey(UsersTable record);
}