#DB Configuration:
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/highconcurrency?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: a
    
  http:
    multipart:
          enabled: true # 默认支持文件上传

  #mvc
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
      
  mail:
    host: smtp.qq.com
    username: 1447076355@qq.com # 这里填写个人的qq邮箱
    password: aghmefjkwysdihfg # 注：这里不是qq邮箱的密码，而是授权码
    default-encoding: UTF-8
#发送地址
mail:
 fromMail:
      addr: 1447076355@qq.com

logging:
  level:
    com:
      hnit: debug
server:
  port: 8086
  tomcat:
    uri-encoding: UTF-8

    
# mybatis缓存
mybatis:
  configuration:
    cache-enabled: true



