package com.lhd.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminname
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.passworld
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String passworld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.phone
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Integer phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminname
     *
     * @return the value of admin.adminname
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminname
     *
     * @param adminname the value for admin.adminname
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.passworld
     *
     * @return the value of admin.passworld
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getPassworld() {
        return passworld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.passworld
     *
     * @param passworld the value for admin.passworld
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setPassworld(String passworld) {
        this.passworld = passworld == null ? null : passworld.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.phone
     *
     * @return the value of admin.phone
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.phone
     *
     * @param phone the value for admin.phone
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }
}