package com.lhd.entity;

import java.io.Serializable;

public class ClassificationofGoodsItem implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.id
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.cId
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.cName
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.inventory
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private Double inventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.images
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationof_goods_item.price
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.id
     *
     * @return the value of classificationof_goods_item.id
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.id
     *
     * @param id the value for classificationof_goods_item.id
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.cId
     *
     * @return the value of classificationof_goods_item.cId
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.cId
     *
     * @param cid the value for classificationof_goods_item.cId
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.cName
     *
     * @return the value of classificationof_goods_item.cName
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.cName
     *
     * @param cname the value for classificationof_goods_item.cName
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.inventory
     *
     * @return the value of classificationof_goods_item.inventory
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public Double getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.inventory
     *
     * @param inventory the value for classificationof_goods_item.inventory
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setInventory(Double inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.images
     *
     * @return the value of classificationof_goods_item.images
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.images
     *
     * @param images the value for classificationof_goods_item.images
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationof_goods_item.price
     *
     * @return the value of classificationof_goods_item.price
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationof_goods_item.price
     *
     * @param price the value for classificationof_goods_item.price
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}