package com.lhd.entity;

import java.io.Serializable;

public class Classificationofgoods implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationofgoods.id
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classificationofgoods.cTypeName
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private String ctypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationofgoods.id
     *
     * @return the value of classificationofgoods.id
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationofgoods.id
     *
     * @param id the value for classificationofgoods.id
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classificationofgoods.cTypeName
     *
     * @return the value of classificationofgoods.cTypeName
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public String getCtypename() {
        return ctypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classificationofgoods.cTypeName
     *
     * @param ctypename the value for classificationofgoods.cTypeName
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setCtypename(String ctypename) {
        this.ctypename = ctypename == null ? null : ctypename.trim();
    }
}