package com.lhd.entity;

import java.util.List;

public class ClassificationType {
	
	/**
	 * 商品详情
	 */
	private List<ClassificationofGoodsItem> classificationofGoodsItem ;
	
	
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification_type.id
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification_type.cTionf_id
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    private Integer ctionfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classification_type.name
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    private String name;
    
    
    public List<ClassificationofGoodsItem> getClassificationofGoodsItem() {
		return classificationofGoodsItem;
	}

	public void setClassificationofGoodsItem(List<ClassificationofGoodsItem> classificationofGoodsItem) {
		this.classificationofGoodsItem = classificationofGoodsItem;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification_type.id
     *
     * @return the value of classification_type.id
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification_type.id
     *
     * @param id the value for classification_type.id
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification_type.cTionf_id
     *
     * @return the value of classification_type.cTionf_id
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public Integer getCtionfId() {
        return ctionfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification_type.cTionf_id
     *
     * @param ctionfId the value for classification_type.cTionf_id
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public void setCtionfId(Integer ctionfId) {
        this.ctionfId = ctionfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classification_type.name
     *
     * @return the value of classification_type.name
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classification_type.name
     *
     * @param name the value for classification_type.name
     *
     * @mbg.generated Sat Nov 16 18:45:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	@Override
	public String toString() {
		return "ClassificationType [classificationofGoodsItem=" + classificationofGoodsItem + ", id=" + id
				+ ", ctionfId=" + ctionfId + ", name=" + name + "]";
	}
    
    
}