package com.lhd.entity;

public class Food {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.id
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.fname
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.normprice
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Double normprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.realprice
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Double realprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.detail
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.ftype
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String ftype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.fstatus
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Integer fstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.id
     *
     * @return the value of food.id
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.id
     *
     * @param id the value for food.id
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.fname
     *
     * @return the value of food.fname
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.fname
     *
     * @param fname the value for food.fname
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.normprice
     *
     * @return the value of food.normprice
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Double getNormprice() {
        return normprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.normprice
     *
     * @param normprice the value for food.normprice
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setNormprice(Double normprice) {
        this.normprice = normprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.realprice
     *
     * @return the value of food.realprice
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Double getRealprice() {
        return realprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.realprice
     *
     * @param realprice the value for food.realprice
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setRealprice(Double realprice) {
        this.realprice = realprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.detail
     *
     * @return the value of food.detail
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.detail
     *
     * @param detail the value for food.detail
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.ftype
     *
     * @return the value of food.ftype
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.ftype
     *
     * @param ftype the value for food.ftype
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setFtype(String ftype) {
        this.ftype = ftype == null ? null : ftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.fstatus
     *
     * @return the value of food.fstatus
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Integer getFstatus() {
        return fstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.fstatus
     *
     * @param fstatus the value for food.fstatus
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setFstatus(Integer fstatus) {
        this.fstatus = fstatus;
    }
}