package com.lhd.entity;

import java.util.Date;

public class Imginfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imginfo.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imginfo.cId
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imginfo.imgPath
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String imgpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imginfo.createTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imginfo.id
     *
     * @return the value of imginfo.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imginfo.id
     *
     * @param id the value for imginfo.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imginfo.cId
     *
     * @return the value of imginfo.cId
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imginfo.cId
     *
     * @param cid the value for imginfo.cId
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imginfo.imgPath
     *
     * @return the value of imginfo.imgPath
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imginfo.imgPath
     *
     * @param imgpath the value for imginfo.imgPath
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imginfo.createTime
     *
     * @return the value of imginfo.createTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imginfo.createTime
     *
     * @param createtime the value for imginfo.createTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

	@Override
	public String toString() {
		return "Imginfo [id=" + id + ", cid=" + cid + ", imgpath=" + imgpath + ", createtime=" + createtime + "]";
	}
    
    
}