package com.lhd.entity;

import java.util.Date;

public class MiaoSha {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.cName
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.price
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.num
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.c_Of_Name
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String cOfName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.createTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.content
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.orderNo
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String orderno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.id
     *
     * @return the value of miao_sha.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.id
     *
     * @param id the value for miao_sha.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.cName
     *
     * @return the value of miao_sha.cName
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.cName
     *
     * @param cname the value for miao_sha.cName
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.price
     *
     * @return the value of miao_sha.price
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.price
     *
     * @param price the value for miao_sha.price
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.num
     *
     * @return the value of miao_sha.num
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.num
     *
     * @param num the value for miao_sha.num
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.c_Of_Name
     *
     * @return the value of miao_sha.c_Of_Name
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getcOfName() {
        return cOfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.c_Of_Name
     *
     * @param cOfName the value for miao_sha.c_Of_Name
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setcOfName(String cOfName) {
        this.cOfName = cOfName == null ? null : cOfName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.createTime
     *
     * @return the value of miao_sha.createTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.createTime
     *
     * @param createtime the value for miao_sha.createTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.content
     *
     * @return the value of miao_sha.content
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.content
     *
     * @param content the value for miao_sha.content
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.orderNo
     *
     * @return the value of miao_sha.orderNo
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.orderNo
     *
     * @param orderno the value for miao_sha.orderNo
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }
}