package com.lhd.entity;

import java.io.Serializable;

public class MiaoSha implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.id
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.cName
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.price
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.images
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.num
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miao_sha.c_Of_Name
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    private String cOfName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.id
     *
     * @return the value of miao_sha.id
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.id
     *
     * @param id the value for miao_sha.id
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.cName
     *
     * @return the value of miao_sha.cName
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.cName
     *
     * @param cname the value for miao_sha.cName
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.price
     *
     * @return the value of miao_sha.price
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.price
     *
     * @param price the value for miao_sha.price
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.images
     *
     * @return the value of miao_sha.images
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.images
     *
     * @param images the value for miao_sha.images
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.num
     *
     * @return the value of miao_sha.num
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.num
     *
     * @param num the value for miao_sha.num
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miao_sha.c_Of_Name
     *
     * @return the value of miao_sha.c_Of_Name
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public String getcOfName() {
        return cOfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miao_sha.c_Of_Name
     *
     * @param cOfName the value for miao_sha.c_Of_Name
     *
     * @mbg.generated Thu Nov 14 11:46:13 CST 2019
     */
    public void setcOfName(String cOfName) {
        this.cOfName = cOfName == null ? null : cOfName.trim();
    }
}