package com.lhd.entity;

import java.util.Date;

public class MiaoshaOrderImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_order_img.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_order_img.createTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_order_img.miaosha_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer miaoshaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_order_img.path
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_order_img.id
     *
     * @return the value of miaosha_order_img.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_order_img.id
     *
     * @param id the value for miaosha_order_img.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_order_img.createTime
     *
     * @return the value of miaosha_order_img.createTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_order_img.createTime
     *
     * @param createtime the value for miaosha_order_img.createTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_order_img.miaosha_id
     *
     * @return the value of miaosha_order_img.miaosha_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getMiaoshaId() {
        return miaoshaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_order_img.miaosha_id
     *
     * @param miaoshaId the value for miaosha_order_img.miaosha_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setMiaoshaId(Integer miaoshaId) {
        this.miaoshaId = miaoshaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_order_img.path
     *
     * @return the value of miaosha_order_img.path
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_order_img.path
     *
     * @param path the value for miaosha_order_img.path
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}