package com.lhd.entity;

import java.util.Date;

public class Mycollection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.userId
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.shopId
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.beginTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Date begintime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.id
     *
     * @return the value of mycollection.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.id
     *
     * @param id the value for mycollection.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.userId
     *
     * @return the value of mycollection.userId
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.userId
     *
     * @param userid the value for mycollection.userId
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.shopId
     *
     * @return the value of mycollection.shopId
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.shopId
     *
     * @param shopid the value for mycollection.shopId
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.beginTime
     *
     * @return the value of mycollection.beginTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.beginTime
     *
     * @param begintime the value for mycollection.beginTime
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }
}