package com.lhd.entity;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.roid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String roid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.address
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.tel
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderTime
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.deliveryTime
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Date deliverytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ps
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String ps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.statue
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Integer statue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.roid
     *
     * @return the value of order.roid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getRoid() {
        return roid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.roid
     *
     * @param roid the value for order.roid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setRoid(String roid) {
        this.roid = roid == null ? null : roid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userid
     *
     * @return the value of order.userid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userid
     *
     * @param userid the value for order.userid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.tel
     *
     * @return the value of order.tel
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.tel
     *
     * @param tel the value for order.tel
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderTime
     *
     * @return the value of order.orderTime
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderTime
     *
     * @param ordertime the value for order.orderTime
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.deliveryTime
     *
     * @return the value of order.deliveryTime
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Date getDeliverytime() {
        return deliverytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.deliveryTime
     *
     * @param deliverytime the value for order.deliveryTime
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setDeliverytime(Date deliverytime) {
        this.deliverytime = deliverytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ps
     *
     * @return the value of order.ps
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getPs() {
        return ps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ps
     *
     * @param ps the value for order.ps
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setPs(String ps) {
        this.ps = ps == null ? null : ps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.statue
     *
     * @return the value of order.statue
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Integer getStatue() {
        return statue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.statue
     *
     * @param statue the value for order.statue
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setStatue(Integer statue) {
        this.statue = statue;
    }
}