package com.lhd.entity;

public class Orderitem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.id
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.roid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private String roid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.num
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.fid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.price
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.id
     *
     * @return the value of orderitem.id
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.id
     *
     * @param id the value for orderitem.id
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.roid
     *
     * @return the value of orderitem.roid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public String getRoid() {
        return roid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.roid
     *
     * @param roid the value for orderitem.roid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setRoid(String roid) {
        this.roid = roid == null ? null : roid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.num
     *
     * @return the value of orderitem.num
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.num
     *
     * @param num the value for orderitem.num
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.fid
     *
     * @return the value of orderitem.fid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.fid
     *
     * @param fid the value for orderitem.fid
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.price
     *
     * @return the value of orderitem.price
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.price
     *
     * @param price the value for orderitem.price
     *
     * @mbg.generated Thu Oct 24 15:52:53 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}