package com.lhd.entity;

public class PromaryTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promary_table.cityCode
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer citycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promary_table.proName
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String proname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promary_table.cityCode
     *
     * @return the value of promary_table.cityCode
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promary_table.cityCode
     *
     * @param citycode the value for promary_table.cityCode
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setCitycode(Integer citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promary_table.proName
     *
     * @return the value of promary_table.proName
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promary_table.proName
     *
     * @param proname the value for promary_table.proName
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }
}