package com.lhd.entity;

import java.util.Date;

public class SysLoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.userName
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.operation
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.ip
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.status
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.create_date
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.id
     *
     * @return the value of sys_login_log.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.id
     *
     * @param id the value for sys_login_log.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.userName
     *
     * @return the value of sys_login_log.userName
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.userName
     *
     * @param username the value for sys_login_log.userName
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.operation
     *
     * @return the value of sys_login_log.operation
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.operation
     *
     * @param operation the value for sys_login_log.operation
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.ip
     *
     * @return the value of sys_login_log.ip
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.ip
     *
     * @param ip the value for sys_login_log.ip
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.status
     *
     * @return the value of sys_login_log.status
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.status
     *
     * @param status the value for sys_login_log.status
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.create_date
     *
     * @return the value of sys_login_log.create_date
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.create_date
     *
     * @param createDate the value for sys_login_log.create_date
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}