package com.lhd.entity;

public class TbPositionCity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_position_city.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_position_city.provice_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Integer proviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_position_city.city_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Long cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_position_city.city_name
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_position_city.short_city_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    private Long shortCityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_position_city.id
     *
     * @return the value of tb_position_city.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_position_city.id
     *
     * @param id the value for tb_position_city.id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_position_city.provice_id
     *
     * @return the value of tb_position_city.provice_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Integer getProviceId() {
        return proviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_position_city.provice_id
     *
     * @param proviceId the value for tb_position_city.provice_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setProviceId(Integer proviceId) {
        this.proviceId = proviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_position_city.city_id
     *
     * @return the value of tb_position_city.city_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_position_city.city_id
     *
     * @param cityId the value for tb_position_city.city_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_position_city.city_name
     *
     * @return the value of tb_position_city.city_name
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_position_city.city_name
     *
     * @param cityName the value for tb_position_city.city_name
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_position_city.short_city_id
     *
     * @return the value of tb_position_city.short_city_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public Long getShortCityId() {
        return shortCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_position_city.short_city_id
     *
     * @param shortCityId the value for tb_position_city.short_city_id
     *
     * @mbg.generated Wed Jan 29 15:02:17 CST 2020
     */
    public void setShortCityId(Long shortCityId) {
        this.shortCityId = shortCityId;
    }
}